#!/bin/bash

cwd=$(dirname "${BASH_SOURCE[0]}")
/bin/bash $cwd/setup/zsh.sh
/bin/bash $cwd/setup/nvm.sh
/bin/bash $cwd/setup/pyenv.sh
/bin/bash $cwd/setup/php.sh
/bin/bash $cwd/setup/alacritty.sh
/bin/bash $cwd/setup/nvim.sh
/bin/bash $cwd/setup/tmux.sh

